name: Download and Split Large File to Repo

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'لینک مستقیم فایل برای دانلود'
        required: true
        type: string
      file_name:
        description: 'نام فایل همراه با پسوند اصلی (مثال: tails.img)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download File
      run: |
        curl -L "${{ github.event.inputs.file_url }}" -o "${{ github.event.inputs.file_name }}"

    - name: Split File into Parts
      run: |
        # ساخت یک پوشه اختصاصی برای پارت‌ها تا مخزن شلوغ نشود
        mkdir -p "downloads/${{ github.event.inputs.file_name }}_parts"
        
        # پارت‌بندی فایل به بخش‌های 90 مگابایتی
        # فایلی به نام file.zip تبدیل می‌شود به file.zip.00, file.zip.01 و غیره
        split -b 90M "${{ github.event.inputs.file_name }}" "downloads/${{ github.event.inputs.file_name }}_parts/${{ github.event.inputs.file_name }}."
        
        # حذف فایل اصلی و حجیم برای جلوگیری از خطای گیت‌هاب
        rm "${{ github.event.inputs.file_name }}"

    - name: Commit and Push Parts
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # اضافه کردن پوشه پارت‌ها به گیت
        git add downloads/
        
        # بررسی اینکه آیا پارتی ایجاد شده است یا خیر
        if git diff --cached --quiet; then
          echo "هیچ پارت جدیدی برای آپلود یافت نشد!"
        else
          git commit -m "تغییرات خودکار: آپلود پارت‌های فایل ${{ github.event.inputs.file_name }}"
          git push
        fi
