name: Download File to Repo

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'لینک مستقیم فایل برای دانلود'
        required: true
        type: string
      file_name:
        description: 'نام فایل همراه با پسوند (مثال: image.png)'
        required: true
        type: string

# اضافه شدن دسترسی نوشتن برای رفع خطای 128
permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download File
      run: |
        curl -L "${{ github.event.inputs.file_url }}" -o "${{ github.event.inputs.file_name }}"

    - name: Commit and Push File
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        if [ -f "${{ github.event.inputs.file_name }}" ]; then
          git add "${{ github.event.inputs.file_name }}"
          git commit -m "تغییرات خودکار: دانلود فایل ${{ github.event.inputs.file_name }}"
          git push
        else
          echo "خطا: فایل یافت نشد!"
          exit 1
        fi
